# Generated by Django 2.2 on 2022-09-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220902_2147'),
        ('orders', '0003_auto_20220903_1224'),
    ]

    operations = [
    ]
